$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
dictionaryDefinitions:
  - name: pfb-words
    path: './pfb-words.txt'
    addWords: true
dictionaries:
  - pfb-words
ignorePaths:
  - '/pfb-words.txt'
